### ISSUE TITLE
Learn how async works in python

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Exchange4Students#13]
Research how async stuff works in python and how we'll need to implement it if we need it

If we need to make stuff async, we need to get rid of pymongo and 'convert' what we have so it conforms to how Motor likes things (Motor is an asynchronous Python driver for MongoDB aka the async version of pymongo): https://docs.mongodb.com/drivers/motor/

**Comment by dcarpenter31** [comment]
Here is a high-level overview of Python async if we end up switching to Motor:
https://www.aeracode.org/2018/02/19/python-async-simplified/

**Comment by dcarpenter31** [comment]
I've been looking further into implementing asynchronous functions for use with our database. It looks like Flask is more or less incompatible as a web framework with asynchronous methods and requests (more research could be done, but after a couple hours of playing around it does not seem likely). There are a lot of popular alternatives that I keep hearing about, such as [Quart](https://pgjones.gitlab.io/quart/), [Sanic](https://sanic.readthedocs.io/en/stable/), or [AIOHTTP](https://docs.aiohttp.org/en/stable/). 

However, that would mean migrating away from Flask, which it seems like we are already somewhat familiar with. Considering that we already are able to get the database working fine for individual demo purposes and that this application is not meant to be a scalable product, we can suffice with Flask. What do you all think?

**Comment by elenirotsides** [comment]
Totally agree! I haven't had any issues with speed and I doubt we'll encounter anything related. I haven't even gotten any massive hard errors that I couldn't debug (often times happens as a result of something not being async when it should be async). This is probably because python operates differently than JavaScript (which is what I'm used to). Like you said, we won't be doing any massive database transactions of any kind, so I think we'll be safe. I trust your instinct and seeing as I haven't done any research about this, I trust your insight more than mine regarding this topic!

**Comment by dcarpenter31** [comment]
thoughts from @SWiessler , @jlora23, and @gracemiguel ?

**Comment by SWiessler** [comment]
word i agree, the less work the better

**Comment by dcarpenter31** [comment]
alright, since a majority agrees I'll close this for now
