### ISSUE TITLE
Need to figure out how to display images on webpage

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Exchange4Students#5]
I read that you shouldn't really be storing images in a database, something about performance. I read that you need to reference an image that's stored as a static file in your folder structure and then add that reference to the database. We need to figure out how to do this, what packages we may need, etc.

**Comment by dcarpenter31** [comment]
See:
- https://gist.github.com/greyli/81d7e5ae6c9baf7f6cdfbf64e8a7c037
- https://flask-wtf.readthedocs.io/en/stable/form.html
- https://github.com/akmamun/flask-mongo-image-upload/blob/master/server.py

**Comment by elenirotsides** [comment]
Edited the title, we can add images to Mongo now, we just can't get them to display on the webpage
