### ISSUE TITLE
Refactor: Category pages into one single html file 

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Exchange4Students#64]
We shouldn't have so many static HTML pages. Instead, we should change all the individual category pages (books.html, furniture.html, etc.) to a single html file called `categories.html` and use Jinja to only display the relevant category. I did this with `view.html` and it worked really well! See that file for details on how I did that and also the `/view/<item_id>` route in `app.py`.

**Comment by elenirotsides** [comment]
Is it possible to do this even though we're routing to a different location? ie `/books` or `/electronics`

**Comment by dcarpenter31** [comment]
This will likely be possible through Flask [blueprints](https://flask.palletsprojects.com/en/1.1.x/tutorial/views/)
